version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bonus_calc_postgres
    environment:
      POSTGRES_DB: bonus_calc_db
      POSTGRES_USER: bonus_user
      POSTGRES_PASSWORD: bonus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bonus_calc_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bonus_calc_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bonuscalc.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bonus_calc_network

volumes:
  postgres_data:

networks:
  bonus_calc_network:
    driver: bridge 